### ISSUE TITLE
语音识别是基于腾讯云开发还是腾讯AI还是其他？

### ISSUE THREAD

**Issue by YJZ-S** [Tencent/Face2FaceTranslator#19]
语音识别是基于腾讯云开发还是腾讯AI还是其他？

**Comment by AminHuang** [comment]
你好，“微信同声传译”插件，是由微信智聆语音团队、微信翻译团队与公众平台联合推出的同传开放接口。

**Comment by xinxibin** [comment]
请问下插件 初始化之后 就会占用一个 socket ，小程序中 最多才两个socket ；
我们小程序 有另外两个 sdk （im、视频通话）
有什么方法 不让插件 占用socket 或者 使用插件只有 主动关闭socket

**Comment by YJZ-S** [comment]
> 你好，“微信同声传译”插件，是由微信智聆语音团队、微信翻译团队与公众平台联合推出的同传开放接口。

Okay thanks
