### ISSUE TITLE
不能导入同声传译插件

### ISSUE THREAD

**Issue by wugaoxue** [Tencent/Face2FaceTranslator#22]
当我在我的微信小程序使用MQTT协议的时候，不能导入同声传译的插件会出现如下的问题。
![QQ截图20190506210526](https://user-images.githubusercontent.com/46316669/57226940-b6e31a80-7042-11e9-84ee-286d5e53e9a7.png)

**Comment by AminHuang** [comment]
上面的报错信息并不是同声传译插件的。

**Comment by gaofei207** [comment]
@wugaoxue   我也遇到mqtt小程序 导入插件后报错， 请问你后来怎么解决的呀？
