### ISSUE TITLE
语音识别过程中，切换小程序至后台，再打开小程序就不能进行语音识别了

### ISSUE THREAD

**Issue by savioryu** [Tencent/Face2FaceTranslator#5]
语音识别过程中，切换小程序至后台，再打开小程序就不能进行语音识别了

调用 manager.start() ，不能进行语音识别，调用 manager.stop()，会报以下错误： 

```
recorder error:  {retcode: -30002, msg: "record manager has paused record"}
```

**Comment by AminHuang** [comment]
麻烦提供一下代码片段。
https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by AminHuang** [comment]
插件v0.0.7版本已修复。
